[theme]
primaryColor = "#10B981"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0FDF4"
textColor = "#334155"
font = "sans serif"

[server]
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false
